#
# Ansible managed
#
all:
  hosts:
    leaf03:
      ansible_host: "10.42.0.23"
      groups: "nxos"
    leaf02:
      ansible_host: "10.42.0.22"
      groups: "nxos"
    leaf01:
      ansible_host: "10.42.0.21"
      groups: "nxos"
    leaf04:
      ansible_host: "10.42.0.24"
      groups: "nxos"
    spine02:
      ansible_host: "10.42.0.12"
      groups: "nxos"
    spine01:
      ansible_host: "10.42.0.11"
      groups: "nxos"
  children:
    nxos:
      hosts:
        10.42.0.23:
        10.42.0.22:
        10.42.0.21:
        10.42.0.24:
        10.42.0.12:
        10.42.0.11:
