#
# Ansible managed
#
all:
  hosts:
    10.42.0.38:
      groups: "ungrouped"
    10.42.0.39:
      groups: "ungrouped"
    10.42.0.34:
      groups: "ungrouped"
    10.42.0.35:
      groups: "ungrouped"
    10.42.0.36:
      groups: "ungrouped"
    10.42.0.37:
      groups: "ungrouped"
    10.42.0.30:
      groups: "ungrouped"
    10.42.0.31:
      groups: "ungrouped"
    10.42.0.32:
      groups: "ungrouped"
    10.42.0.33:
      groups: "ungrouped"
    10.42.0.252:
      groups: "ungrouped"
    10.42.0.251:
      groups: "ungrouped"
    10.42.0.250:
      groups: "ungrouped"
    10.42.0.125:
      groups: "ungrouped"
    10.42.0.124:
      groups: "ungrouped"
    10.42.0.127:
      groups: "ungrouped"
    10.42.0.230:
      groups: "ungrouped"
    10.42.0.123:
      groups: "ungrouped"
    10.42.0.126:
      groups: "ungrouped"
    10.42.0.121:
      groups: "ungrouped"
    10.42.0.120:
      groups: "ungrouped"
    10.42.0.23:
      groups: "nxos"
    10.42.0.22:
      groups: "nxos"
    10.42.0.21:
      groups: "nxos"
    10.42.0.20:
      groups: "ungrouped"
    10.42.0.27:
      groups: "ungrouped"
    10.42.0.26:
      groups: "ungrouped"
    10.42.0.25:
      groups: "ungrouped"
    10.42.0.24:
      groups: "nxos"
    10.42.0.29:
      groups: "ungrouped"
    10.42.0.28:
      groups: "ungrouped"
    10.42.0.122:
      groups: "ungrouped"
    10.42.0.248:
      groups: "ungrouped"
    10.42.0.249:
      groups: "ungrouped"
    10.42.0.244:
      groups: "ungrouped"
    10.42.0.245:
      groups: "ungrouped"
    10.42.0.246:
      groups: "ungrouped"
    10.42.0.247:
      groups: "ungrouped"
    10.42.0.240:
      groups: "ungrouped"
    10.42.0.241:
      groups: "ungrouped"
    10.42.0.242:
      groups: "ungrouped"
    10.42.0.238:
      groups: "ungrouped"
    10.42.0.169:
      groups: "ungrouped"
    10.42.0.168:
      groups: "ungrouped"
    10.42.0.170:
      groups: "ungrouped"
    10.42.0.161:
      groups: "ungrouped"
    10.42.0.160:
      groups: "ungrouped"
    10.42.0.163:
      groups: "ungrouped"
    10.42.0.162:
      groups: "ungrouped"
    10.42.0.165:
      groups: "ungrouped"
    10.42.0.164:
      groups: "ungrouped"
    10.42.0.167:
      groups: "ungrouped"
    10.42.0.166:
      groups: "ungrouped"
    10.42.0.154:
      groups: "ungrouped"
    10.42.0.109:
      groups: "ungrouped"
    10.42.0.108:
      groups: "ungrouped"
    10.42.0.155:
      groups: "ungrouped"
    10.42.0.103:
      groups: "ungrouped"
    10.42.0.102:
      groups: "ungrouped"
    10.42.0.101:
      groups: "ungrouped"
    10.42.0.100:
      groups: "ungrouped"
    10.42.0.107:
      groups: "ungrouped"
    10.42.0.106:
      groups: "ungrouped"
    10.42.0.105:
      groups: "ungrouped"
    10.42.0.104:
      groups: "ungrouped"
    10.42.0.56:
      groups: "ungrouped"
    10.42.0.57:
      groups: "ungrouped"
    10.42.0.54:
      groups: "ungrouped"
    10.42.0.55:
      groups: "ungrouped"
    10.42.0.52:
      groups: "ungrouped"
    10.42.0.53:
      groups: "ungrouped"
    10.42.0.50:
      groups: "ungrouped"
    10.42.0.51:
      groups: "ungrouped"
    10.42.0.150:
      groups: "ungrouped"
    10.42.0.243:
      groups: "ungrouped"
    10.42.0.58:
      groups: "ungrouped"
    10.42.0.59:
      groups: "ungrouped"
    10.42.0.152:
      groups: "ungrouped"
    10.42.0.153:
      groups: "ungrouped"
    10.42.0.223:
      groups: "ungrouped"
    10.42.0.178:
      groups: "ungrouped"
    10.42.0.179:
      groups: "ungrouped"
    10.42.0.176:
      groups: "ungrouped"
    10.42.0.177:
      groups: "ungrouped"
    10.42.0.174:
      groups: "ungrouped"
    10.42.0.175:
      groups: "ungrouped"
    10.42.0.172:
      groups: "ungrouped"
    10.42.0.173:
      groups: "ungrouped"
    localhost:
      groups: "ungrouped"
    10.42.0.171:
      groups: "ungrouped"
    10.42.0.118:
      groups: "ungrouped"
    10.42.0.119:
      groups: "ungrouped"
    10.42.0.227:
      groups: "ungrouped"
    10.42.0.110:
      groups: "ungrouped"
    10.42.0.111:
      groups: "ungrouped"
    10.42.0.112:
      groups: "ungrouped"
    10.42.0.113:
      groups: "ungrouped"
    10.42.0.114:
      groups: "ungrouped"
    10.42.0.115:
      groups: "ungrouped"
    10.42.0.116:
      groups: "ungrouped"
    10.42.0.117:
      groups: "ungrouped"
    10.42.0.45:
      groups: "ungrouped"
    10.42.0.44:
      groups: "ungrouped"
    10.42.0.47:
      groups: "ungrouped"
    10.42.0.46:
      groups: "ungrouped"
    10.42.0.41:
      groups: "ungrouped"
    10.42.0.40:
      groups: "ungrouped"
    10.42.0.43:
      groups: "ungrouped"
    10.42.0.42:
      groups: "ungrouped"
    10.42.0.49:
      groups: "ungrouped"
    10.42.0.48:
      groups: "ungrouped"
    10.42.0.147:
      groups: "ungrouped"
    10.42.0.221:
      groups: "ungrouped"
    10.42.0.183:
      groups: "ungrouped"
    10.42.0.182:
      groups: "ungrouped"
    10.42.0.181:
      groups: "ungrouped"
    10.42.0.180:
      groups: "ungrouped"
    10.42.0.187:
      groups: "ungrouped"
    10.42.0.186:
      groups: "ungrouped"
    10.42.0.185:
      groups: "ungrouped"
    10.42.0.184:
      groups: "ungrouped"
    10.42.0.189:
      groups: "ungrouped"
    10.42.0.188:
      groups: "ungrouped"
    10.42.0.78:
      groups: "ungrouped"
    10.42.0.79:
      groups: "ungrouped"
    10.42.0.129:
      groups: "ungrouped"
    10.42.0.128:
      groups: "ungrouped"
    10.42.0.146:
      groups: "ungrouped"
    10.42.0.70:
      groups: "ungrouped"
    10.42.0.71:
      groups: "ungrouped"
    10.42.0.72:
      groups: "ungrouped"
    10.42.0.73:
      groups: "ungrouped"
    10.42.0.74:
      groups: "ungrouped"
    10.42.0.75:
      groups: "ungrouped"
    10.42.0.76:
      groups: "ungrouped"
    10.42.0.77:
      groups: "ungrouped"
    10.42.0.144:
      groups: "ungrouped"
    10.42.0.143:
      groups: "ungrouped"
    10.42.0.142:
      groups: "ungrouped"
    10.42.0.213:
      groups: "ungrouped"
    10.42.0.141:
      groups: "ungrouped"
    10.42.0.212:
      groups: "ungrouped"
    10.42.0.210:
      groups: "ungrouped"
    10.42.0.140:
      groups: "ungrouped"
    10.42.0.211:
      groups: "ungrouped"
    10.42.0.190:
      groups: "ungrouped"
    10.42.0.191:
      groups: "ungrouped"
    10.42.0.192:
      groups: "ungrouped"
    10.42.0.193:
      groups: "ungrouped"
    10.42.0.194:
      groups: "ungrouped"
    10.42.0.195:
      groups: "ungrouped"
    10.42.0.196:
      groups: "ungrouped"
    10.42.0.197:
      groups: "ungrouped"
    10.42.0.198:
      groups: "ungrouped"
    10.42.0.199:
      groups: "ungrouped"
    10.42.0.219:
      groups: "ungrouped"
    10.42.0.218:
      groups: "ungrouped"
    10.42.0.216:
      groups: "ungrouped"
    10.42.0.132:
      groups: "ungrouped"
    10.42.0.133:
      groups: "ungrouped"
    10.42.0.130:
      groups: "ungrouped"
    10.42.0.131:
      groups: "ungrouped"
    10.42.0.136:
      groups: "ungrouped"
    10.42.0.137:
      groups: "ungrouped"
    10.42.0.69:
      groups: "ungrouped"
    10.42.0.68:
      groups: "ungrouped"
    10.42.0.67:
      groups: "ungrouped"
    10.42.0.66:
      groups: "ungrouped"
    10.42.0.65:
      groups: "ungrouped"
    10.42.0.64:
      groups: "ungrouped"
    10.42.0.63:
      groups: "ungrouped"
    10.42.0.62:
      groups: "ungrouped"
    10.42.0.61:
      groups: "ungrouped"
    10.42.0.60:
      groups: "ungrouped"
    10.42.0.225:
      groups: "ungrouped"
    10.42.0.209:
      groups: "ungrouped"
    10.42.0.200:
      groups: "ungrouped"
    10.42.0.201:
      groups: "ungrouped"
    10.42.0.202:
      groups: "ungrouped"
    10.42.0.203:
      groups: "ungrouped"
    10.42.0.204:
      groups: "ungrouped"
    10.42.0.205:
      groups: "ungrouped"
    10.42.0.206:
      groups: "ungrouped"
    10.42.0.207:
      groups: "ungrouped"
    10.42.0.208:
      groups: "ungrouped"
    10.42.0.151:
      groups: "ungrouped"
    10.42.0.139:
      groups: "ungrouped"
    10.42.0.220:
      groups: "ungrouped"
    10.42.0.92:
      groups: "ungrouped"
    10.42.0.93:
      groups: "ungrouped"
    10.42.0.90:
      groups: "ungrouped"
    10.42.0.91:
      groups: "ungrouped"
    10.42.0.96:
      groups: "ungrouped"
    10.42.0.97:
      groups: "ungrouped"
    10.42.0.94:
      groups: "ungrouped"
    10.42.0.95:
      groups: "ungrouped"
    10.42.0.226:
      groups: "ungrouped"
    10.42.0.98:
      groups: "ungrouped"
    10.42.0.99:
      groups: "ungrouped"
    10.42.0.149:
      groups: "ungrouped"
    10.42.0.148:
      groups: "ungrouped"
    10.42.0.156:
      groups: "ungrouped"
    10.42.0.18:
      groups: "ungrouped"
    10.42.0.19:
      groups: "ungrouped"
    10.42.0.224:
      groups: "ungrouped"
    10.42.0.12:
      groups: "nxos"
    10.42.0.13:
      groups: "ungrouped"
    10.42.0.10:
      groups: "ungrouped"
    10.42.0.11:
      groups: "nxos"
    10.42.0.16:
      groups: "ungrouped"
    10.42.0.17:
      groups: "ungrouped"
    10.42.0.14:
      groups: "ungrouped"
    10.42.0.15:
      groups: "ungrouped"
    10.42.0.214:
      groups: "ungrouped"
    10.42.0.134:
      groups: "ungrouped"
    10.42.0.135:
      groups: "ungrouped"
    10.42.0.157:
      groups: "ungrouped"
    10.42.0.235:
      groups: "ungrouped"
    10.42.0.234:
      groups: "ungrouped"
    10.42.0.237:
      groups: "ungrouped"
    10.42.0.236:
      groups: "ungrouped"
    10.42.0.231:
      groups: "ungrouped"
    10.42.0.215:
      groups: "ungrouped"
    10.42.0.233:
      groups: "ungrouped"
    10.42.0.232:
      groups: "ungrouped"
    10.42.0.239:
      groups: "ungrouped"
    10.42.0.138:
      groups: "ungrouped"
    10.42.0.81:
      groups: "ungrouped"
    10.42.0.80:
      groups: "ungrouped"
    10.42.0.83:
      groups: "ungrouped"
    10.42.0.82:
      groups: "ungrouped"
    10.42.0.85:
      groups: "ungrouped"
    10.42.0.84:
      groups: "ungrouped"
    10.42.0.87:
      groups: "ungrouped"
    10.42.0.86:
      groups: "ungrouped"
    10.42.0.89:
      groups: "ungrouped"
    10.42.0.88:
      groups: "ungrouped"
    10.42.0.158:
      groups: "ungrouped"
    10.42.0.159:
      groups: "ungrouped"
    10.42.0.217:
      groups: "ungrouped"
    10.42.0.8:
      groups: "ungrouped"
    10.42.0.9:
      groups: "ungrouped"
    10.42.0.228:
      groups: "ungrouped"
    10.42.0.229:
      groups: "ungrouped"
    10.42.0.222:
      groups: "ungrouped"
    10.42.0.1:
      groups: "ungrouped"
    10.42.0.2:
      groups: "ungrouped"
    10.42.0.3:
      groups: "ungrouped"
    10.42.0.4:
      groups: "ungrouped"
    10.42.0.5:
      groups: "ungrouped"
    10.42.0.6:
      groups: "ungrouped"
    10.42.0.7:
      groups: "ungrouped"
    10.42.0.145:
      groups: "ungrouped"
  children:
    ungrouped:
      hosts:
        10.42.0.38
        10.42.0.39
        10.42.0.34
        10.42.0.35
        10.42.0.36
        10.42.0.37
        10.42.0.30
        10.42.0.31
        10.42.0.32
        10.42.0.33
        10.42.0.252
        10.42.0.251
        10.42.0.250
        10.42.0.125
        10.42.0.124
        10.42.0.127
        10.42.0.230
        10.42.0.123
        10.42.0.126
        10.42.0.121
        10.42.0.120
        10.42.0.20
        10.42.0.27
        10.42.0.26
        10.42.0.25
        10.42.0.29
        10.42.0.28
        10.42.0.122
        10.42.0.248
        10.42.0.249
        10.42.0.244
        10.42.0.245
        10.42.0.246
        10.42.0.247
        10.42.0.240
        10.42.0.241
        10.42.0.242
        10.42.0.238
        10.42.0.169
        10.42.0.168
        10.42.0.170
        10.42.0.161
        10.42.0.160
        10.42.0.163
        10.42.0.162
        10.42.0.165
        10.42.0.164
        10.42.0.167
        10.42.0.166
        10.42.0.154
        10.42.0.109
        10.42.0.108
        10.42.0.155
        10.42.0.103
        10.42.0.102
        10.42.0.101
        10.42.0.100
        10.42.0.107
        10.42.0.106
        10.42.0.105
        10.42.0.104
        10.42.0.56
        10.42.0.57
        10.42.0.54
        10.42.0.55
        10.42.0.52
        10.42.0.53
        10.42.0.50
        10.42.0.51
        10.42.0.150
        10.42.0.243
        10.42.0.58
        10.42.0.59
        10.42.0.152
        10.42.0.153
        10.42.0.223
        10.42.0.178
        10.42.0.179
        10.42.0.176
        10.42.0.177
        10.42.0.174
        10.42.0.175
        10.42.0.172
        10.42.0.173
        localhost
        10.42.0.171
        10.42.0.118
        10.42.0.119
        10.42.0.227
        10.42.0.110
        10.42.0.111
        10.42.0.112
        10.42.0.113
        10.42.0.114
        10.42.0.115
        10.42.0.116
        10.42.0.117
        10.42.0.45
        10.42.0.44
        10.42.0.47
        10.42.0.46
        10.42.0.41
        10.42.0.40
        10.42.0.43
        10.42.0.42
        10.42.0.49
        10.42.0.48
        10.42.0.147
        10.42.0.221
        10.42.0.183
        10.42.0.182
        10.42.0.181
        10.42.0.180
        10.42.0.187
        10.42.0.186
        10.42.0.185
        10.42.0.184
        10.42.0.189
        10.42.0.188
        10.42.0.78
        10.42.0.79
        10.42.0.129
        10.42.0.128
        10.42.0.146
        10.42.0.70
        10.42.0.71
        10.42.0.72
        10.42.0.73
        10.42.0.74
        10.42.0.75
        10.42.0.76
        10.42.0.77
        10.42.0.144
        10.42.0.143
        10.42.0.142
        10.42.0.213
        10.42.0.141
        10.42.0.212
        10.42.0.210
        10.42.0.140
        10.42.0.211
        10.42.0.190
        10.42.0.191
        10.42.0.192
        10.42.0.193
        10.42.0.194
        10.42.0.195
        10.42.0.196
        10.42.0.197
        10.42.0.198
        10.42.0.199
        10.42.0.219
        10.42.0.218
        10.42.0.216
        10.42.0.132
        10.42.0.133
        10.42.0.130
        10.42.0.131
        10.42.0.136
        10.42.0.137
        10.42.0.69
        10.42.0.68
        10.42.0.67
        10.42.0.66
        10.42.0.65
        10.42.0.64
        10.42.0.63
        10.42.0.62
        10.42.0.61
        10.42.0.60
        10.42.0.225
        10.42.0.209
        10.42.0.200
        10.42.0.201
        10.42.0.202
        10.42.0.203
        10.42.0.204
        10.42.0.205
        10.42.0.206
        10.42.0.207
        10.42.0.208
        10.42.0.151
        10.42.0.139
        10.42.0.220
        10.42.0.92
        10.42.0.93
        10.42.0.90
        10.42.0.91
        10.42.0.96
        10.42.0.97
        10.42.0.94
        10.42.0.95
        10.42.0.226
        10.42.0.98
        10.42.0.99
        10.42.0.149
        10.42.0.148
        10.42.0.156
        10.42.0.18
        10.42.0.19
        10.42.0.224
        10.42.0.13
        10.42.0.10
        10.42.0.16
        10.42.0.17
        10.42.0.14
        10.42.0.15
        10.42.0.214
        10.42.0.134
        10.42.0.135
        10.42.0.157
        10.42.0.235
        10.42.0.234
        10.42.0.237
        10.42.0.236
        10.42.0.231
        10.42.0.215
        10.42.0.233
        10.42.0.232
        10.42.0.239
        10.42.0.138
        10.42.0.81
        10.42.0.80
        10.42.0.83
        10.42.0.82
        10.42.0.85
        10.42.0.84
        10.42.0.87
        10.42.0.86
        10.42.0.89
        10.42.0.88
        10.42.0.158
        10.42.0.159
        10.42.0.217
        10.42.0.8
        10.42.0.9
        10.42.0.228
        10.42.0.229
        10.42.0.222
        10.42.0.1
        10.42.0.2
        10.42.0.3
        10.42.0.4
        10.42.0.5
        10.42.0.6
        10.42.0.7
        10.42.0.145
    nxos:
      hosts:
        10.42.0.23
        10.42.0.22
        10.42.0.21
        10.42.0.24
        10.42.0.12
        10.42.0.11
