#
# Ansible managed
#
all:
  hosts:
    leaf04:
      ansible_host: "leaf04"
    leaf02:
      ansible_host: "leaf02"
    leaf03:
      ansible_host: "leaf03"
    leaf01:
      ansible_host: "leaf01"
    spine02:
      ansible_host: "spine02"
    spine01:
      ansible_host: "spine01"
  children:
    nxos:
      hosts:
        leaf04:
        leaf02:
        leaf03:
        leaf01:
        spine02:
        spine01:

